FROM python:3.14.7

WORKDIR /app


COPY requirements.txt .


RUN pip install -r requirements.txt


COPY src .

CMD python -m infra.manage start_schema && python -m uvicorn controller.main:app --host 0.0.0.0 --port 8000
